# 20 Test Cases for Comprehensive Persona Evaluation (Korean Localized)

TEST_CASES = [
    # -------------------------------------------------------------------------
    # 1. Normal Cases (Basic Functionality Check) - 3 Cases
    # -------------------------------------------------------------------------
    {
        "id": 1,
        "case_type": "Normal",
        "description": "Clear preferences without conflicts",
        "input": {
            "name": "김철수",
            "gender": "남성",
            "age_group": "30대",
            "allergies": "땅콩",
            "preferred_food_categories": "한식",
            "preferred_ingredients": "김치, 돼지고기",
            "extra_text": "매운 음식 좋아하고 든든하게 먹고 싶어요.",
        },
        "expected_behavior": "Must include Peanut(땅콩) in must_avoid. Preferred should include Spicy Korean food.",
    },
    {
        "id": 2,
        "case_type": "Normal",
        "description": "Vegetarian user with clear dislikes",
        "input": {
            "name": "이영희",
            "gender": "여성",
            "age_group": "20대",
            "allergies": "",
            "preferred_food_categories": "채식",
            "preferred_ingredients": "두부, 버섯",
            "extra_text": "고수는 싫어하고 너무 짠 음식은 별로예요.",
        },
        "expected_behavior": "Must avoid Cilantro(고수). Preferred should focus on Vegetarian options.",
    },
    {
        "id": 3,
        "case_type": "Normal",
        "description": "Seafood lover with no restrictions",
        "input": {
            "name": "박민수",
            "gender": "남성",
            "age_group": "40대",
            "allergies": "",
            "preferred_food_categories": "일식, 해산물",
            "preferred_ingredients": "회, 초밥",
            "extra_text": "재료 신선도가 제일 중요해요. 고급스러운 곳 좋아합니다.",
        },
        "expected_behavior": "Persona should reflect a gourmet seafood lover.",
    },
    # -------------------------------------------------------------------------
    # 2. Logic & Contradiction (Reasoning Intelligence) - 5 Cases
    # -------------------------------------------------------------------------
    {
        "id": 4,
        "case_type": "Edge - Contradiction",
        "description": "Allergy vs Preference Conflict (Shellfish)",
        "input": {
            "name": "최모순",
            "gender": "남성",
            "age_group": "30대",
            "allergies": "갑각류",
            "preferred_food_categories": "한식",
            "preferred_ingredients": "새우, 꽃게",  # Conflict!
            "extra_text": "간장게장이 너무 먹고 싶어요.",
        },
        "expected_behavior": "SAFETY FIRST: Must avoid Shellfish/Crab/Shrimp despite preference. Explain the conflict in reasoning.",
    },
    {
        "id": 5,
        "case_type": "Edge - Contradiction",
        "description": "Dietary Restriction vs Request (Vegan vs Meat)",
        "input": {
            "name": "강비건",
            "gender": "여성",
            "age_group": "20대",
            "allergies": "",
            "preferred_food_categories": "비건",
            "preferred_ingredients": "채소",
            "extra_text": "근데 가끔 육즙 가득한 스테이크가 땡길 때가 있어요.",
        },
        "expected_behavior": "Should clarify strictness. If Vegan is primary, Steak should be deprioritized or flagged as a conflict.",
    },
    {
        "id": 6,
        "case_type": "Edge - Contradiction",
        "description": "Spicy Allergy vs Spicy Preference",
        "input": {
            "name": "맵찔이",
            "gender": "남성",
            "age_group": "20대",
            "allergies": "캡사이신",  # Spicy allergy
            "preferred_food_categories": "한식",
            "preferred_ingredients": "떡볶이, 마라탕",  # Very Spicy
            "extra_text": "스트레스 받아서 매운 걸로 풀고 싶네요.",
        },
        "expected_behavior": "SAFETY FIRST: Must avoid Capsaicin/Spicy food. Suggest non-spicy alternatives or warn about health risk.",
    },
    {
        "id": 7,
        "case_type": "Edge - Deep Logic",
        "description": "Implicit Ingredient Conflict (Milk Allergy vs Cream Pasta)",
        "input": {
            "name": "우유No",
            "gender": "여성",
            "age_group": "30대",
            "allergies": "유제품, 우유",
            "preferred_food_categories": "양식",
            "preferred_ingredients": "",
            "extra_text": "꾸덕한 까르보나라나 크림 파스타 종류 좋아해요.",
        },
        "expected_behavior": "Must detect hidden dairy in Cream Pasta. Should suggest Oil-based or Tomato-based pasta instead.",
    },
    {
        "id": 8,
        "case_type": "Edge - Deep Logic",
        "description": "Religious Restriction (Halal vs Pork)",
        "input": {
            "name": "알리",
            "gender": "남성",
            "age_group": "20대",
            "allergies": "",
            "preferred_food_categories": "할랄",
            "preferred_ingredients": "닭고기, 양고기",
            "extra_text": "친구들이 삼겹살집 가자는데 저는 괜찮아요.",
        },
        "expected_behavior": "Halal forbids Pork. Even if user says okay, the persona should likely prefer avoiding it or only eating side dishes. Safety check.",
    },
    # -------------------------------------------------------------------------
    # 3. Ambiguity & Vague Inputs (Creativity Check) - 4 Cases
    # -------------------------------------------------------------------------
    {
        "id": 9,
        "case_type": "Edge - Ambiguity",
        "description": "Zero Preference Input",
        "input": {
            "name": "무관심",
            "gender": "남성",
            "age_group": "50대",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "아무거나 다 상관없네. 그냥 조용한 곳이면 돼.",
        },
        "expected_behavior": "Should create a 'Passive/Easy-going' persona but emphasize 'Quiet Atmosphere'.",
    },
    {
        "id": 10,
        "case_type": "Edge - Ambiguity",
        "description": "Abstract Atmosphere Request",
        "input": {
            "name": "감성파",
            "gender": "여성",
            "age_group": "20대",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "인스타 감성 낭낭하고 힙한 곳으로 부탁해요. 맛은 상관없음.",
        },
        "expected_behavior": "Persona should prioritize Aesthetics/Visuals over Logic/Taste.",
    },
    {
        "id": 11,
        "case_type": "Edge - Ambiguity",
        "description": "Budget Constraint only",
        "input": {
            "name": "짠돌이",
            "gender": "남성",
            "age_group": "20대",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "돈이 없어서요. 무조건 제일 싼 곳으로 가야 합니다.",
        },
        "expected_behavior": "Persona should focus heavily on Price/Cost-effectiveness.",
    },
    {
        "id": 12,
        "case_type": "Edge - Ambiguity",
        "description": "Contradictory Vibe (Quiet + Party)",
        "input": {
            "name": "혼란",
            "gender": "여성",
            "age_group": "30대",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "조용히 대화도 하고 싶은데, 음악은 신나는 파티 분위기였으면 좋겠어요.",
        },
        "expected_behavior": "Should identify the conflict in atmosphere. Might suggest a lounge with separate rooms.",
    },
    # -------------------------------------------------------------------------
    # 4. Social & Cultural Context (Context Awareness) - 4 Cases
    # -------------------------------------------------------------------------
    {
        "id": 13,
        "case_type": "Edge - Context",
        "description": "Business Dinner with Boss",
        "input": {
            "name": "김대리",
            "gender": "남성",
            "age_group": "30대",
            "allergies": "",
            "preferred_food_categories": "한식",
            "preferred_ingredients": "",
            "extra_text": "깐깐하신 부장님 모시는 회식 자리예요. 룸 있어야 하고 서비스 좋아야 합니다.",
        },
        "expected_behavior": "Persona should be Formal, Cautious, and prioritizing Service/Privacy over food taste.",
    },
    {
        "id": 14,
        "case_type": "Edge - Context",
        "description": "Date Night (Blind Date)",
        "input": {
            "name": "소개팅남",
            "gender": "남성",
            "age_group": "20대",
            "allergies": "",
            "preferred_food_categories": "파스타, 스테이크",
            "preferred_ingredients": "",
            "extra_text": "첫 소개팅입니다. 먹기 불편한 음식(수제버거, 갈비 등)은 피해주세요.",
        },
        "expected_behavior": "Must avoid messy foods (Ribs, Burgers). Atmosphere must be Romantic.",
    },
    {
        "id": 15,
        "case_type": "Edge - Context",
        "description": "Foreigner Friend (Non-Spicy)",
        "input": {
            "name": "가이드",
            "gender": "여성",
            "age_group": "20대",
            "allergies": "",
            "preferred_food_categories": "전통 한식",
            "preferred_ingredients": "불고기",
            "extra_text": "매운 거 전혀 못 먹는 외국인 친구들을 데려가요.",
        },
        "expected_behavior": "Must avoid Spicy ingredients (Gochujang, Kimchi). Focus on Bulgogi, Bibimbap (soy sauce version).",
    },
    {
        "id": 16,
        "case_type": "Edge - Context",
        "description": "Hangover Cure",
        "input": {
            "name": "해장필요",
            "gender": "남성",
            "age_group": "40대",
            "allergies": "",
            "preferred_food_categories": "국물 요리",
            "preferred_ingredients": "",
            "extra_text": "어제 과음을 해서요. 속 풀리는 해장국 같은 게 필요합니다.",
        },
        "expected_behavior": "Persona should strongly prefer Soups (Haejang-guk, Pho). Avoid greasy food.",
    },
    # -------------------------------------------------------------------------
    # 5. Constraint Overload (Memory & Attention Check) - 4 Cases
    # -------------------------------------------------------------------------
    {
        "id": 17,
        "case_type": "Edge - Overload",
        "description": "Multiple Allergies (+5 items)",
        "input": {
            "name": "종합병원",
            "gender": "여성",
            "age_group": "30대",
            "allergies": "땅콩, 갑각류, 유제품, 달걀, 밀가루",
            "preferred_food_categories": "",
            "preferred_ingredients": "돼지고기, 닭고기",
            "extra_text": "먹을 수 있는 곳 찾기가 너무 힘드네요.",
        },
        "expected_behavior": "Must list ALL allergies in must_avoid. Very restrictive persona.",
    },
    {
        "id": 18,
        "case_type": "Edge - Overload",
        "description": "Too Many Dislikes",
        "input": {
            "name": "까탈레나",
            "gender": "여성",
            "age_group": "20대",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "오이, 당근, 양파, 마늘, 파 들어간 건 절대 안 먹어요.",
        },
        "expected_behavior": "Must avoid all common Korean aromatics. Very difficult persona.",
    },
    {
        "id": 19,
        "case_type": "Edge - Overload",
        "description": "Specific Brand Rejection",
        "input": {
            "name": "브랜드호불호",
            "gender": "남성",
            "age_group": "30대",
            "allergies": "",
            "preferred_food_categories": "패스트푸드",
            "preferred_ingredients": "",
            "extra_text": "햄버거는 좋은데 맥도날드랑 버거킹은 절대 안 가요. 맘스터치만 갑니다.",
        },
        "expected_behavior": "Must avoid specific brands. Preferred: Mom's Touch.",
    },
    {
        "id": 20,
        "case_type": "Edge - Overload",
        "description": "Complex Mixed Constraints",
        "input": {
            "name": "복잡해",
            "gender": "여성",
            "age_group": "40대",
            "allergies": "복숭아",
            "preferred_food_categories": "일식",
            "preferred_ingredients": "",
            "extra_text": "저탄고지 다이어트 중이라 면이나 밥은 안 돼요. 근데 스시는 먹고 싶어요.",
        },
        "expected_behavior": "Contradiction: Sushi has rice. Reasoning needs to solve this (Sashimi or Keto roll).",
    },
]
