TEST_CASES = [
    # --- 정상 케이스 (Normal Cases) ---
    {
        "id": 1,
        "case_type": "정상",
        "input": {
            "name": "김철수",
            "gender": "남성",
            "age_group": "30대",
            "allergies": ["땅콩"],
            "preferred_food_categories": ["한식", "일식"],
            "preferred_ingredients": ["육류"],
            "extra_text": [],
        },
        "expected_behavior": "땅콩을 must_avoid로 분류. 한식/일식/육류를 preferred로 분류. persona_prompt에 알레르기 제약조건과 선호사항이 명확히 포함.",
    },
    {
        "id": 2,
        "case_type": "정상",
        "input": {
            "name": "이지은",
            "gender": "여성",
            "age_group": "20대",
            "allergies": [],
            "preferred_food_categories": ["양식"],
            "preferred_ingredients": ["치즈", "토마토"],
            "extra_text": ["분위기 좋은 곳 희망"],
        },
        "expected_behavior": "must_avoid는 빈 리스트. 양식/치즈/토마토/분위기 좋은 곳은 preferred로 분류. 협상에 유연한 태도의 페르소나 생성.",
    },
    {
        "id": 3,
        "case_type": "정상",
        "input": {
            "name": "박부장",
            "gender": "남성",
            "age_group": "50대",
            "allergies": ["복숭아"],
            "preferred_food_categories": ["한식"],
            "preferred_ingredients": ["해산물"],
            "extra_text": ["조용한 룸 선호"],
        },
        "expected_behavior": "복숭아는 must_avoid. 한식/해산물/조용한 룸은 preferred. 50대 남성 부장님의 어조 반영 권장.",
    },
    # --- 엣지 케이스 (Edge Cases) ---
    {
        "id": 4,
        "case_type": "엣지케이스",
        "input": {
            "name": "최강경",
            "gender": "남성",
            "age_group": "40대",
            "allergies": ["갑각류", "견과류", "우유"],
            "preferred_food_categories": [],
            "preferred_ingredients": [],
            "extra_text": ["매운 음식 절대 안 됨", "날생선 절대 불가"],
        },
        "expected_behavior": "다중 알레르기(3개)와 extra_text의 강경 표현(2개) 모두 must_avoid로 분류. 매우 까다롭고 강경한 태도의 페르소나 생성.",
    },
    {
        "id": 5,
        "case_type": "엣지케이스",
        "input": {
            "name": "정유연",
            "gender": "여성",
            "age_group": "20대",
            "allergies": [],
            "preferred_food_categories": [],
            "preferred_ingredients": [],
            "extra_text": ["아무거나 다 좋아요"],
        },
        "expected_behavior": "must_avoid와 preferred가 모두 비어있거나 '아무거나'가 preferred에 포함. 매우 수용적인 태도의 페르소나 생성.",
    },
    {
        "id": 6,
        "case_type": "엣지케이스",
        "input": {
            "name": "한까탈",
            "gender": "남성",
            "age_group": "30대",
            "allergies": [],
            "preferred_food_categories": ["양식"],
            "preferred_ingredients": [],
            "extra_text": ["오이는 절대 빼주세요", "파스타 희망", "피자는 별로"],
        },
        "expected_behavior": "오이는 must_avoid. 파스타는 preferred. 피자는 맥락에 따라 preferred에서 제외하거나 낮은 선호도로 반영. extra_text의 복합 요구사항 처리 능력 검증.",
    },
    {
        "id": 7,
        "case_type": "엣지케이스",
        "input": {
            "name": "모순남",
            "gender": "남성",
            "age_group": "30대",
            "allergies": ["돼지고기"],
            "preferred_food_categories": [],
            "preferred_ingredients": ["삼겹살"],  # 모순 상황
            "extra_text": [],
        },
        "expected_behavior": "알레르기(돼지고기)를 우선순위로 두어 must_avoid 설정. 삼겹살 선호는 무시하거나, 알레르기 때문에 먹을 수 없음을 reasoning에 명시하여 안전성 확보.",
    },
    {
        "id": 8,
        "case_type": "엣지케이스",
        "input": {
            "name": "김반반",
            "gender": "여성",
            "age_group": "20대",
            "allergies": [],
            "preferred_food_categories": [],
            "preferred_ingredients": [],
            "extra_text": ["가능하면 싼 곳", "절대 비싼 곳은 안 됨"],
        },
        "expected_behavior": "같은 맥락(가격)에 대해 선호와 금지가 혼재됨. '비싼 곳'을 must_avoid로, '싼 곳'을 preferred로 정확히 분류.",
    },
]
