# 20 Test Cases for Comprehensive Persona Evaluation

TEST_CASES = [
    # -------------------------------------------------------------------------
    # 1. Normal Cases (Basic Functionality Check) - 3 Cases
    # -------------------------------------------------------------------------
    {
        "id": 1,
        "type": "Normal",
        "description": "Clear preferences without conflicts",
        "input": {
            "name": "김철수",
            "gender": "Male",
            "age_group": "30s",
            "allergies": "Peanut",
            "preferred_food_categories": "Korean",
            "preferred_ingredients": "Kimchi, Pork",
            "extra_text": "I love spicy food and want a hearty meal.",
        },
        "expected_behavior": "Must include Peanut in must_avoid. Preferred should include Spicy Korean food.",
    },
    {
        "id": 2,
        "type": "Normal",
        "description": "Vegetarian user with clear dislikes",
        "input": {
            "name": "이영희",
            "gender": "Female",
            "age_group": "20s",
            "allergies": "",
            "preferred_food_categories": "Vegetarian",
            "preferred_ingredients": "Tofu, Mushrooms",
            "extra_text": "I hate cilantro and overly salty food.",
        },
        "expected_behavior": "Must avoid Cilantro. Preferred should focus on Vegetarian options.",
    },
    {
        "id": 3,
        "type": "Normal",
        "description": "Seafood lover with no restrictions",
        "input": {
            "name": "박민수",
            "gender": "Male",
            "age_group": "40s",
            "allergies": "",
            "preferred_food_categories": "Japanese, Seafood",
            "preferred_ingredients": "Sashimi, Sushi",
            "extra_text": "Freshness is key. I enjoy high-end dining.",
        },
        "expected_behavior": "Persona should reflect a gourmet seafood lover.",
    },
    # -------------------------------------------------------------------------
    # 2. Logic & Contradiction (Reasoning Intelligence) - 5 Cases
    # -------------------------------------------------------------------------
    {
        "id": 4,
        "type": "Edge - Contradiction",
        "description": "Allergy vs Preference Conflict (Shellfish)",
        "input": {
            "name": "최모순",
            "gender": "Male",
            "age_group": "30s",
            "allergies": "Shellfish",
            "preferred_food_categories": "Korean",
            "preferred_ingredients": "Shrimp, Crab",  # Conflict!
            "extra_text": "I really want to eat soy marinated crab (Ganjang-gejang).",
        },
        "expected_behavior": "SAFETY FIRST: Must avoid Shellfish/Crab/Shrimp despite preference. Explain the conflict in reasoning.",
    },
    {
        "id": 5,
        "type": "Edge - Contradiction",
        "description": "Dietary Restriction vs Request (Vegan vs Meat)",
        "input": {
            "name": "강비건",
            "gender": "Female",
            "age_group": "20s",
            "allergies": "",
            "preferred_food_categories": "Vegan",
            "preferred_ingredients": "Vegetables",
            "extra_text": "Sometimes I crave a juicy steak though.",
        },
        "expected_behavior": "Should clarify strictness. If Vegan is primary, Steak should be deprioritized or flagged as a conflict.",
    },
    {
        "id": 6,
        "type": "Edge - Contradiction",
        "description": "Spicy Allergy vs Spicy Preference",
        "input": {
            "name": "맵찔이",
            "gender": "Male",
            "age_group": "20s",
            "allergies": "Capsaicin",  # Spicy allergy
            "preferred_food_categories": "Korean",
            "preferred_ingredients": "Tteokbokki, Mala-tang",  # Very Spicy
            "extra_text": "I want to relieve stress with spicy food.",
        },
        "expected_behavior": "SAFETY FIRST: Must avoid Capsaicin/Spicy food. Suggest non-spicy alternatives or warn about health risk.",
    },
    {
        "id": 7,
        "type": "Edge - Deep Logic",
        "description": "Implicit Ingredient Conflict (Milk Allergy vs Cream Pasta)",
        "input": {
            "name": "우유No",
            "gender": "Female",
            "age_group": "30s",
            "allergies": "Dairy, Milk",
            "preferred_food_categories": "Italian",
            "preferred_ingredients": "",
            "extra_text": "I love Carbonara and Cream Pasta.",
        },
        "expected_behavior": "Must detect hidden dairy in Cream Pasta. Should suggest Oil-based or Tomato-based pasta instead.",
    },
    {
        "id": 8,
        "type": "Edge - Deep Logic",
        "description": "Religious Restriction (Halal vs Pork)",
        "input": {
            "name": "알리",
            "gender": "Male",
            "age_group": "20s",
            "allergies": "",
            "preferred_food_categories": "Halal",
            "preferred_ingredients": "Chicken, Lamb",
            "extra_text": "My friends want to go to a Samgyeopsal (Pork belly) place. I am okay with it.",
        },
        "expected_behavior": "Halal forbids Pork. Even if user says okay, the persona should likely prefer avoiding it or only eating side dishes. Safety check.",
    },
    # -------------------------------------------------------------------------
    # 3. Ambiguity & Vague Inputs (Creativity Check) - 4 Cases
    # -------------------------------------------------------------------------
    {
        "id": 9,
        "type": "Edge - Ambiguity",
        "description": "Zero Preference Input",
        "input": {
            "name": "무관심",
            "gender": "Male",
            "age_group": "50s",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "Anything is fine. Just somewhere quiet.",
        },
        "expected_behavior": "Should create a 'Passive/Easy-going' persona but emphasize 'Quiet Atmosphere'.",
    },
    {
        "id": 10,
        "type": "Edge - Ambiguity",
        "description": "Abstract Atmosphere Request",
        "input": {
            "name": "감성파",
            "gender": "Female",
            "age_group": "20s",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "I need a place with 'Hip' vibes for Instagram. Taste doesn't matter.",
        },
        "expected_behavior": "Persona should prioritize Aesthetics/Visuals over Logic/Taste.",
    },
    {
        "id": 11,
        "type": "Edge - Ambiguity",
        "description": "Budget Constraint only",
        "input": {
            "name": "짠돌이",
            "gender": "Male",
            "age_group": "20s",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "I am broke. Cheapest place possible.",
        },
        "expected_behavior": "Persona should focus heavily on Price/Cost-effectiveness.",
    },
    {
        "id": 12,
        "type": "Edge - Ambiguity",
        "description": "Contradictory Vibe (Quiet + Party)",
        "input": {
            "name": "혼란",
            "gender": "Female",
            "age_group": "30s",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "I want a quiet place to talk but also want a party vibe with loud music.",
        },
        "expected_behavior": "Should identify the conflict in atmosphere. Might suggest a lounge with separate rooms.",
    },
    # -------------------------------------------------------------------------
    # 4. Social & Cultural Context (Context Awareness) - 4 Cases
    # -------------------------------------------------------------------------
    {
        "id": 13,
        "type": "Edge - Context",
        "description": "Business Dinner with Boss",
        "input": {
            "name": "김대리",
            "gender": "Male",
            "age_group": "30s",
            "allergies": "",
            "preferred_food_categories": "Korean",
            "preferred_ingredients": "",
            "extra_text": "Dining with the strict Department Manager. Needs private room, high-end service.",
        },
        "expected_behavior": "Persona should be Formal, Cautious, and prioritizing Service/Privacy over food taste.",
    },
    {
        "id": 14,
        "type": "Edge - Context",
        "description": "Date Night (Blind Date)",
        "input": {
            "name": "소개팅남",
            "gender": "Male",
            "age_group": "20s",
            "allergies": "",
            "preferred_food_categories": "Pasta, Steak",
            "preferred_ingredients": "",
            "extra_text": "First blind date. Nothing messy to eat (no ribs, no burgers).",
        },
        "expected_behavior": "Must avoid messy foods (Ribs, Burgers). Atmosphere must be Romantic.",
    },
    {
        "id": 15,
        "type": "Edge - Context",
        "description": "Foreigner Friend (Non-Spicy)",
        "input": {
            "name": "가이드",
            "gender": "Female",
            "age_group": "20s",
            "allergies": "",
            "preferred_food_categories": "Traditional Korean",
            "preferred_ingredients": "Bulgogi",
            "extra_text": "Bringing foreign friends who can't eat spicy food at all.",
        },
        "expected_behavior": "Must avoid Spicy ingredients (Gochujang, Kimchi). Focus on Bulgogi, Bibimbap (soy sauce version).",
    },
    {
        "id": 16,
        "type": "Edge - Context",
        "description": "Hangover Cure",
        "input": {
            "name": "해장필요",
            "gender": "Male",
            "age_group": "40s",
            "allergies": "",
            "preferred_food_categories": "Soup",
            "preferred_ingredients": "",
            "extra_text": "I drank too much yesterday. Need something for hangover.",
        },
        "expected_behavior": "Persona should strongly prefer Soups (Haejang-guk, Pho). Avoid greasy food.",
    },
    # -------------------------------------------------------------------------
    # 5. Constraint Overload (Memory & Attention Check) - 4 Cases
    # -------------------------------------------------------------------------
    {
        "id": 17,
        "type": "Edge - Overload",
        "description": "Multiple Allergies (+5 items)",
        "input": {
            "name": "종합병원",
            "gender": "Female",
            "age_group": "30s",
            "allergies": "Peanut, Shellfish, Dairy, Egg, Wheat",
            "preferred_food_categories": "",
            "preferred_ingredients": "Pork, Chicken",
            "extra_text": "It's really hard for me to find a place.",
        },
        "expected_behavior": "Must list ALL allergies in must_avoid. Very restrictive persona.",
    },
    {
        "id": 18,
        "type": "Edge - Overload",
        "description": "Too Many Dislikes",
        "input": {
            "name": "까탈레나",
            "gender": "Female",
            "age_group": "20s",
            "allergies": "",
            "preferred_food_categories": "",
            "preferred_ingredients": "",
            "extra_text": "I hate cucumbers, carrots, onions, garlic, and green onions.",
        },
        "expected_behavior": "Must avoid all common Korean aromatics. Very difficult persona.",
    },
    {
        "id": 19,
        "type": "Edge - Overload",
        "description": "Specific Brand Rejection",
        "input": {
            "name": "브랜드호불호",
            "gender": "Male",
            "age_group": "30s",
            "allergies": "",
            "preferred_food_categories": "Fast Food",
            "preferred_ingredients": "",
            "extra_text": "I like burgers but NEVER McDonald's or Burger King. Only Mom's Touch.",
        },
        "expected_behavior": "Must avoid specific brands. Preferred: Mom's Touch.",
    },
    {
        "id": 20,
        "type": "Edge - Overload",
        "description": "Complex Mixed Constraints",
        "input": {
            "name": "복잡해",
            "gender": "Female",
            "age_group": "40s",
            "allergies": "Peach",
            "preferred_food_categories": "Japanese",
            "preferred_ingredients": "",
            "extra_text": "I am on a diet (Low Carb). No noodles, no rice. But I want Sushi.",
        },
        "expected_behavior": "Contradiction: Sushi has rice. Reasoning needs to solve this (Sashimi or Keto roll).",
    },
]
